version: '3'

services:

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - spring-boot-network
    volumes:
      - mongodb_data_container:/data/db

  spring_boot_authorization_roles:
    container_name: spring_boot_authorization_roles
    build:
      context: .
    ports:
      - 8081:8081
    networks:
      - spring-boot-network
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=qa"
    depends_on:
      - mongodb
    restart: always

networks:
  spring-boot-network:
    driver: bridge

volumes:
  mongodb_data_container: